import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarLayout } from "@/app/ui-utils/sidebar-layout"; // Update the path to where SidebarLayout is defined
import {
  Sidebar,
  SidebarHeader,
  SidebarBody,
  SidebarFooter,
  SidebarItem,
} from "@/app/ui-utils/sidebar"; // Update the path to where Sidebar components are defined
import { Button } from "./ui-utils/button";
import { Strong } from "./ui-utils/text";
import { navigation } from "./config/data";
import { Heading, Subheading } from "./ui-utils/heading";
import sidebar from "./components/layout/sidebar";
import SidebarComponent from "./components/layout/sidebar";
import { HomeIcon } from "lucide-react";
import NotificationHandler from "./lib/notification";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "News Application",
  description: "Generated by us",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Define Navbar content

  // Define Navbar content
  const navbar = (
    <div className="w-full flex justify-between items-center">
      <Subheading>Application</Subheading>
      <HomeIcon className="mr-2 text-red" />
      <div>{/* Add more navbar items here if needed */}</div>
    </div>
  );

  // Define Sidebar content
  // const sidebar = (
  //   <Sidebar>
  //     <SidebarHeader>
  //       <h2 className="text-xl font-bold">My App</h2>
  //     </SidebarHeader>
  //     <SidebarBody>
  //       {navigation.map((item, index) => (
  //         <SidebarItem current={item.path === "/"} href={item.path} key={index}>
  //           {item.title}
  //         </SidebarItem>
  //       ))}
  //     </SidebarBody>
  //     <SidebarFooter></SidebarFooter>
  //   </Sidebar>
  // );

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-[100vw] h-[100vh] antialiased`}
      >
        <SidebarLayout navbar={navbar} sidebar={<SidebarComponent />}>
          {/* <div className="p-6 text-zinc-800 dark:text-zinc-200"> */}
          {children}
          <NotificationHandler />
          {/* </div> */}
        </SidebarLayout>
      </body>
    </html>
  );
}
