// export const navigation = [
//   {
//     title: "Home",
//     path: "/",
//     icon: "tabler:smart-home",
//   },
//   {
//     title: "Entertainment",
//     path: "/entertainment",
//     icon: "tabler:mail",
//   },
//   {
//     title: "Political News",
//     path: "/political-news",
//     icon: "tabler:mail",
//   },
//   {
//     title: "Sports",
//     path: "/sports",
//     icon: "tabler:mail",
//   },
//   {
//     title: "Telangana",
//     path: "/telangana",
//     icon: "tabler:mail",
//   },
//   {
//     title: "Andhra Pradesh",
//     path: "/andhra-pradesh",
//     icon: "tabler:mail",
//   },
//   {
//     title: "National News",
//     path: "/national-news",
//     icon: "tabler:mail",
//   },
//   {
//     title: "International News",
//     path: "/international-news",
//     icon: "tabler:mail",
//   },
//   {
//     title: "Business News",
//     path: "/business-news",
//     icon: "tabler:mail",
//   },
//   {
//     title: "Photos",
//     path: "/photos",
//     icon: "tabler:mail",
//   },
//   {
//     title: "Videos",
//     path: "/videos",
//     icon: "tabler:mail",
//   },
//   {
//     title: "General News",
//     path: "/general-news",
//     icon: "tabler:mail",
//   },
// ];

export const navigation = [
  {
    title: "Home",
    teluguTitle: "హోం",
    path: "/",
    icon: "tabler:smart-home",
  },
  {
    title: "Entertainment",
    teluguTitle: "ఎంటర్టైన్మెంట్",
    path: "/entertainment",
    icon: "tabler:mail",
  },
  {
    title: "Political News",
    teluguTitle: "పొలిటికల్ న్యూస్ ",
    path: "/political-news",
    icon: "tabler:mail",
  },
  {
    title: "Sports",
    teluguTitle: "స్పోర్ట్స్",
    path: "/sports",
    icon: "tabler:mail",
  },
  {
    title: "Telangana",
    teluguTitle: "తెలంగాణ",
    path: "/telangana",
    icon: "tabler:mail",
  },
  {
    title: "Andhra Pradesh",
    teluguTitle: "ఆంధ్రప్రదేశ్",
    path: "/andhra-pradesh",
    icon: "tabler:mail",
  },
  {
    title: "National News",
    teluguTitle: "నేషనల్ న్యూస్",
    path: "/national-news",
    icon: "tabler:mail",
  },
  {
    title: "International News",
    teluguTitle: "ఇంటర్నేషనల్ న్యూస్",
    path: "/international-news",
    icon: "tabler:mail",
  },
  {
    title: "Business News",
    teluguTitle: "బిజినెస్ న్యూస్",
    path: "/business-news",
    icon: "tabler:mail",
  },
  {
    title: "Photos",
    teluguTitle: "ఫొటోస్",
    path: "/photos",
    icon: "tabler:mail",
  },
  {
    title: "Videos",
    teluguTitle: "వీడియోస్",
    path: "/videos",
    icon: "tabler:mail",
  },
  {
    title: "General News",
    teluguTitle: "జనరల్ న్యూస్",
    path: "/general-news",
    icon: "tabler:mail",
  },
];
interface SubCategory {
  label: string;
  value: string;
}

interface SubCategories {
  [category: string]: SubCategory[];
}

export const subCategories: SubCategories = {
  national: [
    { label: "Andhra Pradesh", value: "andhra-pradesh" },
    { label: "Arunachal Pradesh", value: "arunachal-pradesh" },
    { label: "Assam", value: "assam" },
    { label: "Bihar", value: "bihar" },
    { label: "Chhattisgarh", value: "chhattisgarh" },
    { label: "Goa", value: "goa" },
    { label: "Gujarat", value: "gujarat" },
    { label: "Haryana", value: "haryana" },
    { label: "Himachal Pradesh", value: "himachal-pradesh" },
    { label: "Jharkhand", value: "jharkhand" },
    { label: "Karnataka", value: "karnataka" },
    { label: "Kerala", value: "kerala" },
    { label: "Madhya Pradesh", value: "madhya-pradesh" },
    { label: "Maharashtra", value: "maharashtra" },
    { label: "Manipur", value: "manipur" },
    { label: "Meghalaya", value: "meghalaya" },
    { label: "Mizoram", value: "mizoram" },
    { label: "Nagaland", value: "nagaland" },
    { label: "Odisha", value: "odisha" },
    { label: "Punjab", value: "punjab" },
    { label: "Rajasthan", value: "rajasthan" },
    { label: "Sikkim", value: "sikkim" },
    { label: "Tamil Nadu", value: "tamil-nadu" },
    { label: "Telangana", value: "telangana" },
    { label: "Tripura", value: "tripura" },
    { label: "Uttar Pradesh", value: "uttar-pradesh" },
    { label: "Uttarakhand", value: "uttarakhand" },
    { label: "West Bengal", value: "west-bengal" },
  ],
  photos: [
    { label: "Latest", value: "latest" },
    { label: "Actress", value: "actress" },
    { label: "Events", value: "events" },
    { label: "Movies", value: "movies" },
    { label: "Actors", value: "actors" },
  ],
  entertainment: [
    { label: "Movie Reviews", value: "movie-reviews" },
    { label: "Press Release", value: "press-release" },
    { label: "Movie Schedules", value: "movie-schedules" },
    { label: "Gossips", value: "gossips" },
    { label: "OTT", value: "ott" },
  ],
  sports: [
    { label: "Cricket", value: "cricket" },
    { label: "Football", value: "football" },
    { label: "Hockey", value: "hockey" },
    { label: "Badminton", value: "badminton" },
    { label: "Kabaddi", value: "kabaddi" },
    { label: "Wrestling", value: "wrestling" },
    { label: "Tennis", value: "tennis" },
    { label: "Boxing", value: "boxing" },
    { label: "Table Tennis", value: "table-tennis" },
    { label: "Volleyball", value: "volleyball" },
    { label: "Chess", value: "chess" },
    { label: "Motor Sports", value: "motor-sports" },
    { label: "Archery", value: "archery" },
  ],
  telangana: [
    { label: "Hyderabad", value: "hyderabad" },
    { label: "Khammam", value: "khammam" },
    { label: "Mahabubnagar", value: "mahabubnagar" },
    { label: "Medak", value: "medak" },
    { label: "Nalgonda", value: "nalgonda" },
    { label: "Nizamabad", value: "nizamabad" },
    { label: "Warangal", value: "warangal" },
    { label: "Adilabad", value: "adilabad" },
    { label: "Karimnagar", value: "karimnagar" },
    { label: "Rangareddy", value: "rangareddy" },
  ],
  "andhra-pradesh": [
    { label: "Anantapur", value: "anantapur" },
    { label: "Chittoor", value: "chittoor" },
    { label: "East Godavari", value: "east-godavari" },
    { label: "Guntur", value: "guntur" },
    { label: "Kadapa", value: "kadapa" },
    { label: "Krishna", value: "krishna" },
    { label: "Kurnool", value: "kurnool" },
    { label: "Nellore", value: "nellore" },
    { label: "Prakasam", value: "prakasam" },
    { label: "Srikakulam", value: "srikakulam" },
    { label: "Visakhapatnam", value: "visakhapatnam" },
    { label: "West Godavari", value: "west-godavari" },
    { label: "Vizianagaram", value: "vizianagaram" },
    { label: "Amaravati (new capital region)", value: "amaravati" },
    { label: "Bapatla", value: "bapatla" },
    { label: "Kakinada", value: "kakinada" },
    { label: "Palnadu", value: "palnadu" },
    { label: "Anakapalli", value: "anakapalli" },
    { label: "Chittoor", value: "chittoor" },
    { label: "Nandyal", value: "nandyal" },
    { label: "Peddapalli", value: "peddapalli" },
    { label: "Rajahmundry", value: "rajahmundry" },
    { label: "Srikakulam", value: "srikakulam" },
    { label: "Nellore", value: "nellore" },
    { label: "Narasaraopet", value: "narasaraopet" },
    { label: "Eluru", value: "eluru" },
  ],
  "political-news": [
    { label: "Indian Political News", value: "indian-political-news" },
  ],
  "international-news": [
    { label: "Global News", value: "global-news" },
    { label: "World Politics", value: "world-politics" },
    { label: "Economics", value: "economics" },
    { label: "Technology", value: "technology" },
    { label: "Environment", value: "environment" },
  ],
  "business-news": [
    { label: "Economy", value: "economy" },
    { label: "Markets", value: "markets" },
    { label: "Startups", value: "startups" },
    { label: "Stock Market", value: "stock-market" },
    { label: "Investment", value: "investment" },
    { label: "Business Leaders", value: "business-leaders" },
  ],
  "general-news": [
    { label: "Breaking News", value: "breaking-news" },
    { label: "Trending", value: "trending" },
    { label: "Local News", value: "local-news" },
    { label: "World News", value: "world-news" },
  ],
  videos: [
    { label: "Latest Videos", value: "latest-videos" },
    { label: "Interviews", value: "interviews" },
    { label: "Documentaries", value: "documentaries" },
    { label: "Behind the Scenes", value: "behind-the-scenes" },
    { label: "Trending", value: "trending" },
  ],
};

export const horizontalBottomNavigation = [
  {
    title: "Home",
    teluguTitle: "హోం",
    path: "/",
    icon: "HomeIcon",
  },
  {
    title: "Short News",
    teluguTitle: "స్క్రీన్ న్యూజ్",
    path: "/short-news",
    icon: "FileIcon",
  },
  {
    title: "Photos",
    teluguTitle: "ఫొటోస్",
    path: "/photos",
    icon: "PhotosIcon",
  },
  // {
  //   title: "Videos",
  //   teluguTitle: "వీడియోస్",
  //   path: "/videos",
  //   icon: "VideosIcon",
  // },
];
